/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pesanhotel;

import java.awt.Color;

/**
 *
 * @author ACER
 */
public class AdminHome extends javax.swing.JFrame {
    
    public static boolean detailkamar101;    
    public static boolean detailkamar102;
    public static boolean detailkamar103;
    public static boolean detailkamar201;
    public static boolean detailkamar202;
    public static boolean detailkamar203;
    
    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        
        detailkamar101 = false;
        detailkamar102 = false;
        detailkamar103 = false;
        detailkamar201 = false;
        detailkamar202 = false;
        detailkamar203 = false;
        
        
        if (Home.sdhdipesan101 == true){
            jLabel4.setText("Pesan");
            jPanel16.setBackground(Color.GREEN);
            jLabel6.setText(CheckOut.nama101);
            jLabel8.setText(CheckOut.notelp101);
        }else{
            jLabel4.setText("Kosong");
            jPanel16.setBackground(Color.RED);
            jLabel6.setText("  -  ");
            jLabel8.setText("  -  ");
        }
        if (Home.sdhdipesan102 == true){
            jLabel11.setText("Pesan");
            jPanel13.setBackground(Color.GREEN);
            jLabel13.setText(CheckOut.nama102);
            jLabel15.setText(CheckOut.notelp102);
        }else{
            jLabel11.setText("Kosong");
            jPanel13.setBackground(Color.RED);
            jLabel13.setText("  -  ");
            jLabel15.setText("  -  ");
        }
        if (Home.sdhdipesan103 == true){
            jLabel20.setText("Pesan");
            jPanel26.setBackground(Color.GREEN);
            jLabel21.setText(CheckOut.nama103);
            jLabel22.setText(CheckOut.notelp103);
        }else{
            jLabel20.setText("Kosong");
            jPanel26.setBackground(Color.RED);
            jLabel21.setText("  -  ");
            jLabel22.setText("  -  ");
        }
        if (Home.sdhdipesan201 == true){
            jLabel27.setText("Pesan");
            jPanel31.setBackground(Color.GREEN);
            jLabel28.setText(CheckOut.nama201);
            jLabel29.setText(CheckOut.notelp201);
        }else{
            jLabel27.setText("Kosong");
            jPanel31.setBackground(Color.RED);
            jLabel28.setText("  -  ");
            jLabel29.setText("  -  ");
        }
        if (Home.sdhdipesan202 == true){
            jLabel34.setText("Pesan");
            jPanel21.setBackground(Color.GREEN);
            jLabel35.setText(CheckOut.nama202);
            jLabel36.setText(CheckOut.notelp202);
        }else{
            jLabel34.setText("Kosong");
            jPanel21.setBackground(Color.RED);
            jLabel35.setText("  -  ");
            jLabel36.setText("  -  ");
        }
        if (Home.sdhdipesan203 == true){
            jLabel41.setText("Pesan");
            jPanel14.setBackground(Color.GREEN);
            jLabel42.setText(CheckOut.nama203);
            jLabel43.setText(CheckOut.notelp203);
        }else{
            jLabel41.setText("Kosong");
            jPanel14.setBackground(Color.RED);
            jLabel42.setText("  -  ");
            jLabel43.setText("  -  ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cek Kamar");

        jPanel1.setBackground(new java.awt.Color(64, 165, 120));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hallo, Admin!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 0, 233, 48);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kamar 101");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 73, 80, 16);

        jLabel5.setText("Nama :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 132, 50, 16);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(107, 132, 70, 16);

        jLabel7.setText("No hp :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 162, 50, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(107, 162, 70, 16);

        jButton1.setText("Detail Kamar 101");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 190, 160, 23);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kamar 102");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 230, 80, 20);

        jButton2.setText("Detail Kamar 102");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 350, 160, 23);

        jButton3.setText("Detail Kamar 103");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(280, 190, 160, 23);

        jButton4.setText("Detail Kamar 202");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 190, 160, 23);

        jButton5.setText("Detail Kamar 203");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(520, 350, 160, 23);

        jButton6.setText("Detail Kamar 201");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(280, 350, 160, 23);

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setText("Keluar");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 400, 72, 23);

        jPanel2.setBackground(new java.awt.Color(0, 103, 105));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(250, 0, 250, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 750, 30);

        jPanel4.setBackground(new java.awt.Color(0, 103, 105));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 70, 160, 23);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(102, 255, 102));
        jPanel14.setLayout(null);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("jLabel41");
        jPanel14.add(jLabel41);
        jLabel41.setBounds(10, 3, 50, 16);

        jPanel5.add(jPanel14);
        jPanel14.setBounds(90, 0, 70, 30);

        jLabel38.setText("Status :");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(520, 260, 160, 22);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(20, 130, 160, 23);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(20, 160, 160, 23);

        jPanel8.setBackground(new java.awt.Color(0, 103, 105));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(20, 230, 160, 23);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(null);

        jLabel10.setText("Status :");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(10, 2, 50, 16);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(100, 3, 50, 16);

        jPanel13.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13);
        jPanel13.setBounds(90, 0, 70, 30);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(20, 260, 160, 22);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(null);

        jLabel12.setText("Nama :");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(10, 3, 50, 16);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(93, 3, 60, 16);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(20, 290, 160, 22);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(null);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("jLabel15");
        jPanel11.add(jLabel15);
        jLabel15.setBounds(93, 3, 60, 16);

        jLabel14.setText("No hp :");
        jPanel11.add(jLabel14);
        jLabel14.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel11);
        jPanel11.setBounds(20, 320, 160, 22);

        jPanel15.setBackground(new java.awt.Color(0, 103, 105));
        jPanel15.setLayout(null);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Kamar 202");
        jPanel15.add(jLabel30);
        jLabel30.setBounds(50, 3, 70, 16);

        jPanel1.add(jPanel15);
        jPanel15.setBounds(520, 70, 160, 23);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(102, 255, 102));
        jPanel16.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");
        jPanel16.add(jLabel4);
        jLabel4.setBounds(10, 3, 50, 16);

        jPanel12.add(jPanel16);
        jPanel16.setBounds(90, 0, 70, 30);

        jLabel46.setText("Status :");
        jPanel12.add(jLabel46);
        jLabel46.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel12);
        jPanel12.setBounds(20, 100, 160, 22);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setLayout(null);

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("jLabel43");
        jPanel17.add(jLabel43);
        jLabel43.setBounds(93, 3, 60, 16);

        jLabel40.setText("No hp :");
        jPanel17.add(jLabel40);
        jLabel40.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel17);
        jPanel17.setBounds(520, 320, 160, 22);

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setLayout(null);

        jLabel26.setText("No hp :");
        jPanel18.add(jLabel26);
        jLabel26.setBounds(10, 3, 50, 16);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("jLabel29");
        jPanel18.add(jLabel29);
        jLabel29.setBounds(93, 3, 60, 16);

        jPanel1.add(jPanel18);
        jPanel18.setBounds(280, 320, 160, 23);

        jPanel19.setBackground(new java.awt.Color(0, 103, 105));
        jPanel19.setLayout(null);

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Kamar 203");
        jPanel19.add(jLabel37);
        jLabel37.setBounds(50, 3, 80, 16);

        jPanel1.add(jPanel19);
        jPanel19.setBounds(520, 230, 160, 22);

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel20.setLayout(null);

        jPanel21.setBackground(new java.awt.Color(102, 255, 102));
        jPanel21.setLayout(null);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("jLabel34");
        jPanel21.add(jLabel34);
        jLabel34.setBounds(10, 3, 50, 16);

        jPanel20.add(jPanel21);
        jPanel21.setBounds(90, 0, 70, 30);

        jLabel31.setText("Status :");
        jPanel20.add(jLabel31);
        jLabel31.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel20);
        jPanel20.setBounds(520, 100, 160, 22);

        jPanel22.setBackground(new java.awt.Color(204, 204, 204));
        jPanel22.setLayout(null);

        jLabel33.setText("No hp :");
        jPanel22.add(jLabel33);
        jLabel33.setBounds(10, 3, 50, 16);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("jLabel36");
        jPanel22.add(jLabel36);
        jLabel36.setBounds(90, 3, 60, 16);

        jPanel1.add(jPanel22);
        jPanel22.setBounds(520, 160, 160, 22);

        jPanel23.setBackground(new java.awt.Color(204, 204, 204));
        jPanel23.setLayout(null);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("jLabel22");
        jPanel23.add(jLabel22);
        jLabel22.setBounds(93, 3, 60, 16);

        jLabel52.setText("No hp :");
        jPanel23.add(jLabel52);
        jLabel52.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel23);
        jPanel23.setBounds(280, 160, 160, 23);

        jPanel24.setBackground(new java.awt.Color(0, 103, 105));
        jPanel24.setLayout(null);

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Kamar 103");
        jPanel24.add(jLabel53);
        jLabel53.setBounds(50, 3, 80, 16);

        jPanel1.add(jPanel24);
        jPanel24.setBounds(280, 70, 160, 23);

        jPanel25.setBackground(new java.awt.Color(204, 204, 204));
        jPanel25.setLayout(null);

        jPanel26.setBackground(new java.awt.Color(102, 255, 102));
        jPanel26.setLayout(null);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("jLabel20");
        jPanel26.add(jLabel20);
        jLabel20.setBounds(10, 3, 50, 16);

        jPanel25.add(jPanel26);
        jPanel26.setBounds(90, 0, 70, 30);

        jLabel55.setText("Status :");
        jPanel25.add(jLabel55);
        jLabel55.setBounds(10, 3, 50, 16);

        jPanel1.add(jPanel25);
        jPanel25.setBounds(280, 100, 160, 22);

        jPanel27.setBackground(new java.awt.Color(204, 204, 204));
        jPanel27.setLayout(null);

        jLabel56.setText("Nama :");
        jPanel27.add(jLabel56);
        jLabel56.setBounds(10, 3, 50, 16);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("jLabel21");
        jPanel27.add(jLabel21);
        jLabel21.setBounds(93, 3, 60, 16);

        jPanel1.add(jPanel27);
        jPanel27.setBounds(279, 130, 160, 22);

        jPanel28.setBackground(new java.awt.Color(204, 204, 204));
        jPanel28.setLayout(null);

        jLabel58.setText("Nama :");
        jPanel28.add(jLabel58);
        jLabel58.setBounds(10, 3, 50, 16);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Jlabel35");
        jPanel28.add(jLabel35);
        jLabel35.setBounds(90, 3, 60, 16);

        jPanel1.add(jPanel28);
        jPanel28.setBounds(520, 130, 160, 22);

        jPanel29.setBackground(new java.awt.Color(0, 103, 105));
        jPanel29.setLayout(null);

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Kamar 201");
        jPanel29.add(jLabel60);
        jLabel60.setBounds(50, 3, 80, 16);

        jPanel1.add(jPanel29);
        jPanel29.setBounds(280, 230, 160, 22);

        jPanel30.setBackground(new java.awt.Color(204, 204, 204));
        jPanel30.setLayout(null);

        jPanel31.setBackground(new java.awt.Color(102, 255, 102));
        jPanel31.setLayout(null);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("jLabel27");
        jPanel31.add(jLabel27);
        jLabel27.setBounds(10, 3, 50, 16);

        jPanel30.add(jPanel31);
        jPanel31.setBounds(90, 0, 70, 30);

        jLabel59.setText("Status :");
        jPanel30.add(jLabel59);
        jLabel59.setBounds(10, 3, 60, 16);

        jPanel1.add(jPanel30);
        jPanel30.setBounds(280, 260, 160, 22);

        jPanel32.setBackground(new java.awt.Color(204, 204, 204));
        jPanel32.setLayout(null);

        jLabel47.setText("Nama :");
        jPanel32.add(jLabel47);
        jLabel47.setBounds(10, 3, 50, 16);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("jLabel28");
        jPanel32.add(jLabel28);
        jLabel28.setBounds(93, 3, 60, 16);

        jPanel1.add(jPanel32);
        jPanel32.setBounds(280, 290, 160, 22);

        jPanel33.setBackground(new java.awt.Color(204, 204, 204));
        jPanel33.setLayout(null);

        jLabel49.setText("Nama :");
        jPanel33.add(jLabel49);
        jLabel49.setBounds(10, 3, 50, 16);

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("jLabel42");
        jPanel33.add(jLabel42);
        jLabel42.setBounds(93, 3, 60, 16);

        jPanel1.add(jPanel33);
        jPanel33.setBounds(520, 290, 160, 22);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Melihat Detail Kamar");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(250, 390, 220, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Home.sdhdipesan101 == true){
            detailkamar101 = true;
            this.dispose();
            DetaiKamar dk = new DetaiKamar();
            dk.setVisible(true);
            dk.pack();
            dk.setLocationRelativeTo(null);
            dk.setDefaultCloseOperation(DetaiKamar.EXIT_ON_CLOSE);
        }else{
            jLabel44.setForeground(Color.RED);
            jLabel44.setText("Kamar 101 Belum di pesan");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (Home.sdhdipesan103 == true){
            detailkamar103 = true;
            this.dispose();
            DetaiKamar dk = new DetaiKamar();
            dk.setVisible(true);
            dk.pack();
            dk.setLocationRelativeTo(null);
            dk.setDefaultCloseOperation(DetaiKamar.EXIT_ON_CLOSE);
        }else{
            jLabel44.setForeground(Color.RED);
            jLabel44.setText("Kamar 103 Belum di pesan");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Home.sdhdipesan102 == true){
            detailkamar102 = true;
            this.dispose();
            DetaiKamar dk = new DetaiKamar();
            dk.setVisible(true);
            dk.pack();
            dk.setLocationRelativeTo(null);
            dk.setDefaultCloseOperation(DetaiKamar.EXIT_ON_CLOSE);
        }else{
            jLabel44.setForeground(Color.RED);
            jLabel44.setText("Kamar 102 Belum di pesan");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (Home.sdhdipesan201 == true){
            detailkamar201 = true;
            this.dispose();
            DetaiKamar dk = new DetaiKamar();
            dk.setVisible(true);
            dk.pack();
            dk.setLocationRelativeTo(null);
            dk.setDefaultCloseOperation(DetaiKamar.EXIT_ON_CLOSE);
        }else{
            jLabel44.setForeground(Color.RED);
            jLabel44.setText("Kamar 201 Belum di pesan");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (Home.sdhdipesan202 == true){
            detailkamar202 = true;
            this.dispose();
            DetaiKamar dk = new DetaiKamar();
            dk.setVisible(true);
            dk.pack();
            dk.setLocationRelativeTo(null);
            dk.setDefaultCloseOperation(DetaiKamar.EXIT_ON_CLOSE);
        }else{
            jLabel44.setForeground(Color.RED);
            jLabel44.setText("Kamar 202 Belum di pesan");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (Home.sdhdipesan203 == true){
            detailkamar203 = true;
            this.dispose();
            DetaiKamar dk = new DetaiKamar();
            dk.setVisible(true);
            dk.pack();
            dk.setLocationRelativeTo(null);
            dk.setDefaultCloseOperation(DetaiKamar.EXIT_ON_CLOSE);
        }else{
            jLabel44.setForeground(Color.RED);
            jLabel44.setText("Kamar 203 Belum di pesan");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
