/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pesanhotel;
import java.awt.*;
import java.util.Map;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author ACER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public static String namahome;
    
    
    public static String no_kamar2;
    public static int harga;
    public static int totharga;
    public static int tothari;
    public static String strtotharga;
    public static String ceklabel_hari;
    public static String ceknohp;
    public static String cekemail;
    public static String nohp;
    public static String email;
    public static String tglpsn;
    public static String blnpsn;
    public static String thnpsn;
    public static String tgldpsn;
    public static String blndpsn;
    public static String thndpsn;
    public static String psnhari;
    public static String lharga;
    public static int pajak;
    public static String strpajak;
    public static int tothargaril;
    public static String strtothargaril;
    
    public static boolean sdhdipesan;
    
    public static boolean sdhdipesan101;
    public static boolean sdhdipesan102;
    public static boolean sdhdipesan103;
    public static boolean sdhdipesan201;
    public static boolean sdhdipesan202;
    public static boolean sdhdipesan203;
    
    public static String cekbulandipesan;
    public static String cekbulanpesan;
    
    
    
    public Home() {
        initComponents();
        Map<String, String> userDetails = Register.database.get(Login.ambilusername);
        namahome = userDetails.get("nama");
        jLabel21.setText(namahome);
        sdhdipesan = false;
//        System.out.println(sdhdipesan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        no_kamar = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Beige Gold Luxury Home Key Real Estate Logo_20240611_125717_0003.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel18.setMinimumSize(new java.awt.Dimension(100, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesan Kamar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 103, 105));
        jPanel1.setLayout(null);

        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(83, 0, 390, 20);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wellcome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 30, 190, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Beige Gold Luxury Home Key Real Estate Logo_20240611_125717_0003.png"))); // NOI18N
        jLabel19.setText("jLabel18");
        jLabel19.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel19.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(390, -70, 200, 100);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Beige Gold Luxury Home Key Real Estate Logo_20240611_125717_0003.png"))); // NOI18N
        jLabel20.setText("jLabel18");
        jLabel20.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel20.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel20);
        jLabel20.setBounds(-65, 10, 200, 100);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(190, 70, 190, 16);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 91));

        jPanel2.setBackground(new java.awt.Color(64, 165, 120));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        jButton1.setText("Pesan");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(320, 260, 72, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(470, 30, 72, 22);

        jButton4.setText("pesanan sebeumnya");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(29, 320, 170, 23);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(380, 30, 72, 22);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal yang dipesan : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 140, 16);

        no_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203" }));
        no_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_kamarActionPerformed(evt);
            }
        });
        jPanel2.add(no_kamar);
        no_kamar.setBounds(290, 130, 72, 22);

        jButton2.setText("Cek Harga");
        jButton2.setToolTipText("");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(29, 260, 110, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal pesan :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 70, 100, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No kamar:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 130, 120, 16);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 220, 120, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bulan");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(300, 10, 40, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tahun");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(480, 10, 40, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(390, 10, 50, 16);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024" }));
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(470, 70, 72, 22);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Berapa Hari:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 160, 120, 16);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(290, 30, 72, 22);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(290, 190, 100, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(380, 70, 72, 22);

        jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
        });
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });
        jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(jTextField);
        jTextField.setBounds(290, 220, 100, 22);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(290, 160, 100, 22);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("No hp:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 190, 100, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(290, 70, 72, 22);

        jButton3.setText("Keluar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(460, 320, 72, 23);
        jPanel2.add(jLabel14);
        jLabel14.setBounds(150, 262, 160, 20);

        jLabel6.setText("Rp.200000/hari");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(370, 132, 140, 20);

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel17);
        jLabel17.setBounds(210, 322, 190, 20);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 560, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_kamarActionPerformed
        // TODO add your handling code here:
        no_kamar2 = no_kamar.getSelectedItem().toString();;
        switch (no_kamar2){
            case "101":
                harga = 200000;
                break;
            case "102":
                harga = 210000;
                break;
            case "103":
                harga = 220000;
                break;
            case "201":
                harga = 150000;
                break;
            case "202":
                harga = 200000;
                break;
            case "203":
                harga = 250000;
                break;
            }
        jLabel6.setText("Rp." + harga + "/hari");
    }//GEN-LAST:event_no_kamarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        no_kamar2 = (String) no_kamar.getSelectedItem();
        switch (no_kamar2){
            case "101":
                harga = 200000;
                break;
            case "102":
                harga = 210000;
                break;
            case "103":
                harga = 220000;
                break;
            case "201":
                harga = 150000;
                break;
            case "202":
                harga = 200000;
                break;
            case "203":
                harga = 250000;
                break;
            }
        ceklabel_hari = jTextField2.getText();
        if (ceklabel_hari.isEmpty()){
            jLabel14.setText("Jumlah Hari Belum di input");
            jLabel14.setForeground(Color.RED);
        }
        else{
            tothari = Integer.parseInt(jTextField2.getText());
            totharga = harga*tothari;
            strtotharga = Integer.toString(totharga);
            jLabel14.setText("Rp." + strtotharga);
            jLabel14.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sdhdipesan = false;
//        System.out.println(sdhdipesan);
        
        tglpsn = (String) jComboBox1.getSelectedItem();
        blnpsn = (String) jComboBox2.getSelectedItem();
        thnpsn = (String) jComboBox3.getSelectedItem();
        tgldpsn = (String) jComboBox4.getSelectedItem();
        blndpsn = (String) jComboBox5.getSelectedItem();
        thndpsn = (String) jComboBox6.getSelectedItem();
        psnhari = jTextField2.getText();
        
        no_kamar2 = (String) no_kamar.getSelectedItem();
        switch (no_kamar2){
            case "101":
                if (sdhdipesan101 == true){
                    sdhdipesan =  true;
                }else{
                harga = 200000;
                }
                break;
            case "102":
                if (sdhdipesan102 == true){
                    sdhdipesan =  true;
                }else{
                    harga = 210000;
                }
                break;
            case "103":
                if (sdhdipesan103 == true){
                    sdhdipesan =  true;
                }else{
                    harga = 220000;
                }
                break;
            case "201":
                if (sdhdipesan201 == true){
                    sdhdipesan =  true;
                }else{
                    harga = 150000;
                }
                break;
            case "202":
                if (sdhdipesan202 == true){
                    sdhdipesan =  true;
                }else{
                    harga = 200000;
                }
                break;
            case "203":
                if (sdhdipesan203 == true){
                    sdhdipesan =  true;
                }else{
                    harga = 250000;
                }
                break;
        }
            
//        System.out.println(sdhdipesan);
        
        if (sdhdipesan == true){
            jLabel14.setText("Kamar Telah dipesan");
            jLabel14.setForeground(Color.RED);
        }else{
            
        lharga = Integer.toString(harga);
                
        ceklabel_hari = jTextField2.getText();
        ceknohp = jTextField1.getText();
        cekemail = jTextField.getText();
                
        if (ceklabel_hari.isEmpty() || ceknohp.isEmpty() || cekemail.isEmpty() || ceknohp.equals("Harus Diisi") || cekemail.equals("Harus Diisi")){
            
            if (ceklabel_hari.isEmpty()){
                jLabel14.setText("Jumlah Hari Belum di input");
                jLabel14.setForeground(Color.RED);
                }else{
                tothari = Integer.parseInt(jTextField2.getText());
                totharga = harga*tothari;
                strtotharga = Integer.toString(totharga);
                jLabel14.setText("Rp." + strtotharga);
                jLabel14.setForeground(Color.BLACK);


                pajak = totharga * 10 / 100;
                strpajak = Integer.toString(pajak);

                tothargaril = totharga + pajak;
                strtothargaril = Integer.toString(tothargaril);
            }
            
            if (ceknohp.isEmpty()){
                jTextField1.setText("Harus Diisi");
                jTextField1.setForeground(Color.RED);
            }
            if (cekemail.isEmpty()){
                jTextField.setText("Harus Diisi");
                jTextField.setForeground(Color.RED);
            }
        }
        else{
            tothari = Integer.parseInt(jTextField2.getText());
            totharga = harga*tothari;
            strtotharga = Integer.toString(totharga);
            jLabel14.setText(strtotharga);
            jLabel14.setForeground(Color.BLACK);


            pajak = totharga * 10 / 100;
            strpajak = Integer.toString(pajak);

            tothargaril = totharga + pajak;
            strtothargaril = Integer.toString(tothargaril);
            
            nohp = jTextField1.getText();
            email = jTextField.getText();
                
            
            
            this.dispose();
            CheckOut co = new CheckOut();
            co.setVisible(true);
            co.pack();
            co.setLocationRelativeTo(null);
            co.setDefaultCloseOperation(CheckOut.EXIT_ON_CLOSE);
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setForeground(Color.BLACK);
        if (jTextField1.getText().equals("Harus Diisi")){
            jTextField1.setText("");
        }
        
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFocusGained
        // TODO add your handling code here:
        jTextField.setForeground(Color.BLACK);
        if (jTextField.getText().equals("Harus Diisi")){
            jTextField.setText("");
        }
    }//GEN-LAST:event_jTextFieldFocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextField.requestFocus();
            jButton1.doClick();
        }
    }//GEN-LAST:event_jTextFieldKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (CheckOut.databaseco.containsKey(namahome)) {
            this.dispose();
            SelesaiPesan sp = new SelesaiPesan();
            sp.setVisible(true);
            sp.pack();
            sp.setLocationRelativeTo(null);
            sp.setDefaultCloseOperation(SelesaiPesan.EXIT_ON_CLOSE);
        }else{
            jLabel17.setText("Anda belum pernah memesan");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
//        cektglpesan = jComboBox4.getSelectedItem().toString();
//        int agk = Integer.parseInt(cektglpesan);
//        boolean a = false;
//        boolean b = false;
//        boolean c = false;
//        if (cektglpesan.equals("31") && a == false){
//            String[] items = {"01", "03", "05", "07", "08", "10", "12"};
//            jComboBox5.setModel(new DefaultComboBoxModel<>(items));
//            a = true;
//            b = false;
//            c = false;
//        } else if (agk < 30 && b == false){
//            String[] items = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12"};
//            jComboBox5.setModel(new DefaultComboBoxModel<>(items));  
//            a = false;
//            b = true;
//            c = false;
//        } else if (agk <= 30 && b == false){
//            String[] items = {"01","03", "04", "05", "06", "07", "08", "09", "10", "11", "12"};
//            jComboBox5.setModel(new DefaultComboBoxModel<>(items));
//            a = false;
//            b = false;
//            c = true;
//        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your hanjComboBox5ActionPerformeddling code here:
        cekbulanpesan = jComboBox5.getSelectedItem().toString();
        if (cekbulanpesan.equals("01") || cekbulanpesan.equals("3") || cekbulanpesan.equals("5") || cekbulanpesan.equals("7") || cekbulanpesan.equals("8") || cekbulanpesan.equals("10") || cekbulanpesan.equals("12")) {
            String[] tanggal = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12","13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29", "30", "31"};
            jComboBox4.setModel(new DefaultComboBoxModel<>(tanggal));
        } else if (cekbulanpesan.equals("02") ) {
            String[] tanggal = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12","13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29"};
            jComboBox4.setModel(new DefaultComboBoxModel<>(tanggal));
        } else {
            String[] tanggal = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12","13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29", "30"};
            jComboBox4.setModel(new DefaultComboBoxModel<>(tanggal));
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if (cekbulanpesan.equals("01") || cekbulanpesan.equals("3") || cekbulanpesan.equals("5") || cekbulanpesan.equals("7") || cekbulanpesan.equals("8") || cekbulanpesan.equals("10") || cekbulanpesan.equals("12")) {
            String[] tanggal = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12","13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29", "30", "31"};
            jComboBox4.setModel(new DefaultComboBoxModel<>(tanggal));
        } else if (cekbulanpesan.equals("02") ) {
            String[] tanggal = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12","13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29"};
            jComboBox4.setModel(new DefaultComboBoxModel<>(tanggal));
        } else {
            String[] tanggal = {"01","02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12","13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
            "25", "26", "27", "28", "29", "30"};
            jComboBox4.setModel(new DefaultComboBoxModel<>(tanggal));
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> no_kamar;
    // End of variables declaration//GEN-END:variables
}
